version: "3.8"

networks:
  net_async:

services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: asyncdb
    ports:
      - "5432:5432"
    networks:
      net_async:
        aliases:
          - database
